import { LogoDef } from './types';

/**
 * LOGO CONFIGURATION
 * 
 * Logos are now loaded from the /public/logos/ directory.
 * The ID here corresponds to the filename: e.g., 'CANON' -> /logos/Canon.svg
 * 
 * To add a new logo:
 * 1. Add your SVG file to public/logos/Name.svg
 * 2. Add an entry here with id: 'Name'.
 */

export const LOGOS: Record<string, LogoDef> = {
  CANON: {
    id: 'Canon',
    label: 'Canon',
  },
  FUJIFILM: {
    id: 'Fujifilm',
    label: 'Fujifilm',
  },
  GOOGLE: {
    id: 'Google',
    label: 'Google',
  },
  APPLE: {
    id: 'Apple',
    label: 'Apple',
  },
  HASSELBLAD: {
    id: 'Hasselblad',
    label: 'Hasselblad',
  },
  NIKON: {
    id: 'Nikon',
    label: 'Nikon',
  },
  OLYMPUS: {
    id: 'Olympus',
    label: 'Olympus',
  },
  PANASONIC: {
    id: 'Panasonic',
    label: 'Panasonic',
  },
  SONY: {
    id: 'Sony',
    label: 'Sony',
  },
  DEFAULT: {
    id: 'Camera',
    label: 'Default',
  },
};

export const TRANSLATIONS = {
  en: {
    upload: 'Upload Photo',
    drop: 'Drop your photo here',
    settings: 'Settings',
    model: 'Model',
    lens: 'Lens',
    focalLength: 'Focal Length',
    fNumber: 'Aperture',
    iso: 'ISO',
    exposureTime: 'Shutter',
    params: 'Shooting Params',
    date: 'Date',
    gps: 'Location',
    style: 'Banner Style',
    black: 'Black',
    white: 'White',
    blur: 'Blur',
    adaptive: 'Adaptive',
    download: 'Download',
    processing: 'Processing...',
    blurIntensity: 'Blur Intensity',
    contentLayout: 'Layout',
    show: 'Show',
    left: 'Left',
    right: 'Right',
    text: 'Text',
    editData: 'Edit Data',
    logo: 'Logo',
    auto: 'Auto Detect',
    customLogo: 'Custom Logo (SVG)',
    uploadLogo: 'Upload SVG',
    unknown: 'Unknown Camera',
    line1: 'Top',
    line2: 'Bottom',
    off: 'Hidden',
    logoPos: 'Logo Position',
    logoLeft: 'Left',
    logoRight: 'Right',
  },
  zh: {
    upload: '上传照片',
    drop: '拖拽照片到此处',
    settings: '设置',
    model: '机型',
    lens: '镜头',
    focalLength: '焦距',
    fNumber: '光圈',
    iso: 'ISO',
    exposureTime: '快门',
    params: '拍摄参数',
    date: '日期',
    gps: '位置',
    style: '横幅样式',
    black: '黑色',
    white: '白色',
    blur: '毛玻璃',
    adaptive: '自适应',
    download: '下载',
    processing: '处理中...',
    blurIntensity: '模糊程度',
    contentLayout: '布局与顺序',
    show: '显示',
    left: '左侧',
    right: '右侧',
    text: '文本',
    editData: '编辑数据内容',
    logo: 'Logo 图标',
    auto: '自动识别',
    customLogo: '自定义 Logo (SVG)',
    uploadLogo: '上传 SVG',
    unknown: '未知相机',
    line1: '上层',
    line2: '下层',
    off: '隐藏',
    logoPos: 'Logo 位置',
    logoLeft: '左侧',
    logoRight: '右侧',
  },
  ja: {
    upload: '写真をアップロード',
    drop: 'ここに写真をドロップ',
    settings: '設定',
    model: 'モデル',
    lens: 'レンズ',
    focalLength: '焦点距離',
    fNumber: '絞り',
    iso: 'ISO',
    exposureTime: 'シャッター',
    params: '撮影パラメータ',
    date: '日付',
    gps: '位置情報',
    style: 'バナースタイル',
    black: '黒',
    white: '白',
    blur: 'ぼかし',
    adaptive: '適応',
    download: 'ダウンロード',
    processing: '処理中...',
    blurIntensity: 'ぼかし強度',
    contentLayout: 'レイアウト',
    show: '表示',
    left: '左',
    right: '右',
    text: 'テキスト',
    editData: 'データ編集',
    logo: 'ロゴ',
    auto: '自動検出',
    customLogo: 'カスタムロゴ (SVG)',
    uploadLogo: 'SVGをアップロード',
    unknown: '不明なカメラ',
    line1: '上',
    line2: '下',
    off: 'オフ',
    logoPos: 'ロゴ位置',
    logoLeft: '左',
    logoRight: '右',
  },
  ko: {
    upload: '사진 업로드',
    drop: '여기에 사진을 드롭하세요',
    settings: '설정',
    model: '모델',
    lens: '렌즈',
    focalLength: '초점 거리',
    fNumber: '조리개',
    iso: 'ISO',
    exposureTime: '셔터',
    params: '촬영 매개변수',
    date: '날짜',
    gps: '위치',
    style: '배너 스타일',
    black: '검정',
    white: '흰색',
    blur: '블러',
    adaptive: '적응형',
    download: '다운로드',
    processing: '처리 중...',
    blurIntensity: '블러 강도',
    contentLayout: '레이아웃',
    show: '표시',
    left: '왼쪽',
    right: '오른쪽',
    text: '텍스트',
    editData: '데이터 편집',
    logo: '로고',
    auto: '자동 감지',
    customLogo: '사용자 지정 로고 (SVG)',
    uploadLogo: 'SVG 업로드',
    unknown: '알 수 없는 카메라',
    line1: '상단',
    line2: '하단',
    off: '끄기',
    logoPos: '로고 위치',
    logoLeft: '왼쪽',
    logoRight: '오른쪽',
  },
  es: {
    upload: 'Subir Foto',
    drop: 'Suelta tu foto aquí',
    settings: 'Ajustes',
    model: 'Modelo',
    lens: 'Lente',
    focalLength: 'Distancia Focal',
    fNumber: 'Apertura',
    iso: 'ISO',
    exposureTime: 'Obturador',
    params: 'Parámetros',
    date: 'Fecha',
    gps: 'Ubicación',
    style: 'Estilo de Banner',
    black: 'Negro',
    white: 'Blanco',
    blur: 'Desenfoque',
    adaptive: 'Adaptable',
    download: 'Descargar',
    processing: 'Procesando...',
    blurIntensity: 'Intensidad',
    contentLayout: 'Diseño',
    show: 'Mostrar',
    left: 'Izq',
    right: 'Der',
    text: 'Texto',
    editData: 'Editar Datos',
    logo: 'Logo',
    auto: 'Auto',
    customLogo: 'Logo Personalizado (SVG)',
    uploadLogo: 'Subir SVG',
    unknown: 'Cámara Desconocida',
    line1: 'Arriba',
    line2: 'Abajo',
    off: 'Apagado',
    logoPos: 'Posición del Logo',
    logoLeft: 'Izquierda',
    logoRight: 'Derecha',
  },
  de: {
    upload: 'Foto hochladen',
    drop: 'Foto hier ablegen',
    settings: 'Einstellungen',
    model: 'Modell',
    lens: 'Objektiv',
    focalLength: 'Brennweite',
    fNumber: 'Blende',
    iso: 'ISO',
    exposureTime: 'Verschlusszeit',
    params: 'Aufnahmeparameter',
    date: 'Datum',
    gps: 'Standort',
    style: 'Banner-Stil',
    black: 'Schwarz',
    white: 'Weiß',
    blur: 'Weichzeichner',
    adaptive: 'Adaptiv',
    download: 'Herunterladen',
    processing: 'Verarbeitung...',
    blurIntensity: 'Intensität',
    contentLayout: 'Layout',
    show: 'Anzeigen',
    left: 'Links',
    right: 'Rechts',
    text: 'Text',
    editData: 'Daten bearbeiten',
    logo: 'Logo',
    auto: 'Automatisch',
    customLogo: 'Benutzerdefiniertes Logo (SVG)',
    uploadLogo: 'SVG hochladen',
    unknown: 'Unbekannte Kamera',
    line1: 'Oben',
    line2: 'Unten',
    off: 'Aus',
    logoPos: 'Logo-Position',
    logoLeft: 'Links',
    logoRight: 'Rechts',
  },
  fr: {
    upload: 'Télécharger',
    drop: 'Déposez votre photo ici',
    settings: 'Paramètres',
    model: 'Modèle',
    lens: 'Objectif',
    focalLength: 'Focale',
    fNumber: 'Ouverture',
    iso: 'ISO',
    exposureTime: 'Vitesse',
    params: 'Paramètres',
    date: 'Date',
    gps: 'Emplacement',
    style: 'Style de bannière',
    black: 'Noir',
    white: 'Blanc',
    blur: 'Flou',
    adaptive: 'Adaptatif',
    download: 'Télécharger',
    processing: 'Traitement...',
    blurIntensity: 'Intensité',
    contentLayout: 'Mise en page',
    show: 'Afficher',
    left: 'Gauche',
    right: 'Droite',
    text: 'Texte',
    editData: 'Modifier les données',
    logo: 'Logo',
    auto: 'Auto',
    customLogo: 'Logo personnalisé (SVG)',
    uploadLogo: 'Télécharger SVG',
    unknown: 'Caméra inconnue',
    line1: 'Haut',
    line2: 'Bas',
    off: 'Désactivé',
    logoPos: 'Position du Logo',
    logoLeft: 'Gauche',
    logoRight: 'Droite',
  },
};